package opencodeomo

import (
	"fmt"
	"os"
	"sort"
	"strings"

	i18n "github.com/rzbdz/newgate/lib/i18n"
	"github.com/rzbdz/newgate/lib/style"
	cliapi "github.com/rzbdz/newgate/modules/cli/extension"
	configapi "github.com/rzbdz/newgate/modules/config"
	"github.com/rzbdz/newgate/modules/config/domain"
	"github.com/rzbdz/newgate/modules/config/resolve"
	"github.com/rzbdz/newgate/modules/config/store"
	"github.com/rzbdz/newgate/modules/gateway/controlplane"
)

type omoCommand struct{}

var _ cliapi.Command = (*omoCommand)(nil)

func (omoCommand) Names() []string { return []string{"omo", "slots"} }

func (omoCommand) Run(host cliapi.Host, args []string) int {
	return cmdOmo(host, args)
}

// cmdOmo 管 omo（opencode 的 oh-my-openagent 插件）的 intra-agent 槽位。
//
// 槽位键（omo-sisyphus / cat-deep …）是**模块贡献的动态角色**：接管时由
// omo 模块注册给框架（runtime/injection/omo.go），框架把它们和档位一视同仁
// 地解析。所以这个命令只做三件事——看一眼现状、改缺省归属、解释解析结果。
//
// 用户不需要记键名：不带参数就是列表。
func cmdOmo(host cliapi.Host, args []string) int {
	if len(args) == 0 {
		return omoList()
	}
	switch args[0] {
	case "ls", "list":
		return omoList()
	case "use", "set":
		if len(args) < 3 {
			return host.Die(64, i18n.T("Usage: newgate omo use <slot key> <@other-key|tier|provider/model>", nil))
		}
		return omoUse(host, args[1], args[2], true)
	case "unset", "reset":
		if len(args) < 2 {
			return host.Die(64, i18n.T("Usage: newgate omo unset <slot key>", nil))
		}
		return omoUse(host, args[1], "", false)
	case "mode":
		if len(args) < 2 {
			return omoMode(host, "")
		}
		return omoMode(host, args[1])
	case "explain":
		if len(args) < 2 {
			return host.Die(64, i18n.T("Usage: newgate omo explain <slot key>", nil))
		}
		return omoExplain(host, args[1])
	}
	return host.Die(64, i18n.T("Usage: newgate omo [ls | use <key> <binding> | unset <key> | mode current|suggested | explain <key>]", nil))
}

func omoRegistry() *OmoSlots {
	reg := ReadOmoSlots()
	if reg == nil {
		fmt.Println(style.Item(style.Skip, i18n.T("no slot registry at {file}", i18n.A{"file": SlotsFile()})))
		fmt.Println(style.Hint(i18n.T("generated by one takeover: newgate on opencode", nil)))
		os.Exit(0)
	}
	return reg
}

// omoList 槽位清单使用纵向卡片。键、槽位和模型标识符都是不可分割的信息，
// 不能为了六列表格从中间硬切；属性放在后续缩进行。
func omoList() int {
	reg := omoRegistry()
	fmt.Println(style.Title("newgate omo",
		i18n.N("{n} slot key · mode {mode}", "{n} slot keys · mode {mode}",
			len(reg.Slots), i18n.A{"n": len(reg.Slots), "mode": omoModeName(reg)})))
	fmt.Println(style.Rule(78))
	fmt.Println(style.Hint(i18n.T("current=takeover status · suggested=recommendation · switch: newgate omo mode <mode>", nil)))

	fmt.Println()
	for _, s := range reg.Slots {
		eff := reg.SlotBinding(s.Key)
		if _, ok := reg.Overrides[s.Key]; ok {
			eff = style.Cyan(eff) + style.Dim("*")
		}
		was := dash(s.Was)
		if s.Variant != "" {
			was += style.Dim("(" + s.Variant + ")")
		}
		sug := style.Dim(dash(s.Suggested))
		if s.Suggested != "" && s.Suggested != s.Current {
			sug = style.Yellow(s.Suggested)
		}
		fmt.Print(omoSlotCard(s.Key, s.Kind+"/"+s.Name, was, s.Current, sug, eff))
	}
	if len(reg.Overrides) > 0 {
		fmt.Println(style.Hint(i18n.T("* has an override (written by newgate omo use), highest priority", nil)))
	}

	var diff []OmoSlot
	for _, s := range reg.Slots {
		if s.Suggested != "" && s.Suggested != s.Current {
			diff = append(diff, s)
		}
	}
	if len(diff) > 0 {
		fmt.Print(style.Section(i18n.N("{n} slot differs from the recommendation",
			"{n} slots differ from the recommendation", len(diff), i18n.A{"n": len(diff)})) +
			style.Dim("   newgate omo mode suggested "+i18n.T("adopt them all", nil)) + "\n")
		for _, s := range diff {
			fmt.Println(style.Item(style.Skip, s.Key))
			line := s.Current + " → " + style.Yellow(s.Suggested)
			if s.Why != "" {
				line += " · " + style.Dim(s.Why)
			}
			fmt.Println(style.Hint(line))
		}
	}
	fmt.Println()
	fmt.Println(style.Hint(i18n.T("writing the key name directly in a profile works too: omo-sisyphus=@normal, terra/medium", nil)))
	return 0
}

func omoSlotCard(key, slot, was, current, suggested, effective string) string {
	var out strings.Builder
	identifierLine := func(label, value string) {
		out.WriteString("    " + style.Dim(label) + " " + value + "\n")
	}
	out.WriteString("  " + style.Mark(style.Skip) + " " + key + "\n")
	identifierLine(i18n.T("slot", nil), slot)
	identifierLine(i18n.T("before takeover", nil), was)
	identifierLine(i18n.T("now", nil), current)
	identifierLine(i18n.T("suggested", nil), suggested)
	identifierLine(i18n.T("effective", nil), effective)
	return out.String()
}

func omoModeName(reg *OmoSlots) string {
	if reg.Mode == "suggested" {
		return "suggested"
	}
	return "current"
}

// omoDiffCount 建议档位与现状不同的键数（有覆盖的不算——那些已经定了）。
func omoDiffCount(reg *OmoSlots) int {
	if reg == nil {
		return 0
	}
	n := 0
	for _, s := range reg.Slots {
		if _, over := reg.Overrides[s.Key]; over {
			continue
		}
		if s.Suggested != "" && s.Suggested != s.Current {
			n++
		}
	}
	return n
}

func dash(s string) string {
	if s == "" {
		return "-"
	}
	return s
}

// omoUse 写/删一个覆盖。value 为空表示删除。
func omoUse(host cliapi.Host, key, value string, set bool) int {
	reg := ReadOmoSlots()
	if reg == nil {
		return host.Die(65, i18n.T("no omo slot registry; run newgate on opencode first", nil))
	}
	if _, ok := reg.SlotOf(key); !ok {
		return host.Die(64, i18n.T("no such slot key {key} (list them with newgate omo)",
			i18n.A{"key": key}))
	}
	if set {
		if err := validateBindingValue(value); err != nil {
			return host.Die(64, err.Error())
		}
		if reg.Overrides == nil {
			reg.Overrides = map[string]string{}
		}
		reg.Overrides[key] = value
	} else {
		delete(reg.Overrides, key)
	}
	if err := WriteOmoSlots(reg); err != nil {
		return host.Die(70, i18n.Ef(err, "cannot write the registry: {err}", nil).Error())
	}
	if set {
		fmt.Println(style.Item(style.OK,
			i18n.T("{key} default binding → {value}",
				i18n.A{"key": key, "value": style.Cyan(value)})))
	} else {
		fmt.Println(style.Item(style.OK,
			i18n.T("{key} override removed, back to {mode}",
				i18n.A{"key": key, "mode": omoModeName(reg)})))
	}
	host.NotifyProxy()
	fmt.Println(style.Hint(i18n.T("takes effect within 1 second; if the profile spells out this key, the profile wins", nil)))
	return 0
}

func validateBindingValue(v string) error {
	if strings.HasPrefix(v, "@") {
		key := strings.TrimPrefix(v, "@")
		if key == "" || strings.ContainsAny(key, "/ ") {
			return i18n.E("a reference is written as @key (e.g. @normal), got {value}",
				i18n.A{"value": v})
		}
		return nil
	}
	if strings.Contains(v, "/") {
		if _, err := domain.ParseBindingString(v); err != nil {
			return err
		}
		return nil
	}
	if !domain.IsKnownRole(v) {
		return i18n.E("{value} is neither a tier (heavy/normal/mid/light/vision), "+
			"nor a registered dynamic role key, nor provider/model", i18n.A{"value": v})
	}
	return nil
}

func omoMode(host cliapi.Host, mode string) int {
	reg := omoRegistry()
	if mode == "" {
		fmt.Println(style.Title("newgate omo mode", omoModeName(reg)))
		fmt.Println(style.Rule(64))
		t := style.NewTable(i18n.T("mode", nil), i18n.T("meaning", nil))
		t.Row("current", style.Dim(i18n.T("each key keeps the status it had at takeover (the default; behaviour unchanged)", nil)))
		t.Row("suggested", style.Dim(i18n.T("each key follows the recommendation, derived from model build and variant strength", nil)))
		fmt.Print(t.String())
		fmt.Println(style.Hint(i18n.T("switch: newgate omo mode current|suggested", nil)))
		return 0
	}
	switch mode {
	case "current", "suggested":
	default:
		return host.Die(64, i18n.T("mode only accepts current / suggested", nil))
	}
	reg.Mode = mode
	if err := WriteOmoSlots(reg); err != nil {
		return host.Die(70, i18n.Ef(err, "cannot write the registry: {err}", nil).Error())
	}
	fmt.Println(style.Item(style.OK, i18n.T("mode → {mode}", i18n.A{"mode": style.Cyan(mode)})))
	n := 0
	for _, s := range reg.Slots {
		if _, ok := reg.Overrides[s.Key]; ok {
			continue
		}
		if s.Suggested != "" && s.Suggested != s.Current {
			n++
		}
	}
	if mode == "suggested" {
		fmt.Println(style.Hint(i18n.N(
			"{n} key's binding changes with it (overridden ones are unaffected); not happy? newgate omo mode current",
			"{n} keys' bindings change with it (overridden ones are unaffected); not happy? newgate omo mode current",
			n, i18n.A{"n": n})))
	} else {
		fmt.Println(style.Hint(i18n.T("back to the status recorded at takeover", nil)))
	}
	host.NotifyProxy()
	return 0
}

// omoExplain 把一个槽位键解析成实际的 fallback 链——「为什么不是我想的那个」
// 只能靠这个回答（docs/04-configuration.md）。
func omoExplain(host cliapi.Host, key string) int {
	reg := ReadOmoSlots()
	if reg == nil {
		return host.Die(65, i18n.T("no omo slot registry; run newgate on opencode first", nil))
	}
	// 先装快照：角色键是 store.Load 里跟着刷新的（core/roleprov），
	// 不先装一次的话 IsKnownRole 会说不认识我们自己刚注册的键。
	snap, err := store.Load()
	if err != nil {
		return host.Die(65, err.Error())
	}
	if !domain.IsKnownRole(key) {
		return host.Die(64, i18n.T("{key} is not a known role key (list them with newgate omo ls)",
			i18n.A{"key": key}))
	}
	st := snap.State
	heads := map[string][]string{st.DefaultProfile: {i18n.T("default", nil)}}
	for agent, p := range st.Active {
		heads[p] = append(heads[p], agent)
	}
	names := make([]string, 0, len(heads))
	for h := range heads {
		names = append(names, h)
	}
	sort.Strings(names)

	sub := i18n.T("module dynamic role, not an omo slot", nil)
	if sl, ok := reg.SlotOf(key); ok {
		sub = sl.Kind + "/" + sl.Name
	}
	fmt.Println(style.Title("newgate omo "+key, sub))
	fmt.Println(style.Rule(64))

	if sl, ok := reg.SlotOf(key); ok {
		t := style.NewTable(i18n.T("field", nil), i18n.T("value", nil))
		t.Row(i18n.T("before takeover", nil), style.Dim(dash(sl.Was)+" "+dash(sl.Variant)))
		t.Row(i18n.T("now", nil), sl.Current)
		t.Row(i18n.T("suggested", nil), dash(sl.Suggested))
		t.Row(i18n.T("effective", nil), style.Cyan(reg.SlotBinding(key)))
		fmt.Print(t.String())
		if sl.Why != "" {
			fmt.Println(style.Hint(i18n.T("why: {why}", i18n.A{"why": sl.Why})))
		}
	}

	// 熔断表快照直接读控制面叶子（见 cliapi.Host 的说明：LiveRouting 不再走界面）。
	_, doc := controlplane.State()
	available, rank := doc.Available(), doc.Rank()
	for _, head := range names {
		fmt.Print(style.Section(i18n.T("chain head {head}", i18n.A{"head": head})) +
			style.Dim("   "+strings.Join(heads[head], ", ")) + "\n")
		steps, skips := resolve.BuildChain(key, snap.Profiles, snap.Providers, resolve.Opts{
			Active:    head,
			Available: available,
			Rank:      rank,
			MaxSteps:  st.Chain.Attempts(),
		})
		if len(steps) == 0 {
			fmt.Println(style.Item(style.Bad, i18n.T("no available candidate", nil)))
		} else {
			configapi.PrintChain(steps)
		}
		if len(skips) > 0 {
			configapi.PrintSkips(skips)
		}
	}
	return 0
}
