package opencodeomo

// 本文件是 omo 槽位贡献给 web 界面的那一面：**哪个槽位现在用哪个模型**。
//
// 它是**发行版模块**贡献的第一张卡片（此前四个贡献者全在内核）。路径完全一样：
// `Optional(viewapi.Capability)` + 登记一个产出函数，前端一个字都不用改——
// 这正是 lib/view 那句「加一个模块的界面不需要改前端」要成立的地方。
//
// # 为什么不是六列表（CLI 那边特意用了竖版卡片）
//
// `newgate omo` 的注释写得很清楚：键、槽位与模型标识符是不可分割的信息，终端里
// 六列会从中间硬切，所以它排成竖版卡片。浏览器里那条约束不成立——这张表横向可
// 滚、格子不折行（见 kinds/Table.svelte），标识符不会被切断。但列数仍然要挑：
// 这里少了 CLI 卡片里的两行：
//
//   - **before takeover**（was）：那是迁移与回滚时才要看的东西，属于「翻旧账」；
//   - **now**（current）单独一列没必要——`effective` 才是**实际生效**的那个值
//     （override > mode > current，见 SlotBinding），把两个都摆出来只会让人问
//     「到底哪个算数」。
//
// # 只读
//
// 写槽位归属是 `newgate omo use/unset` 的语义（改 overrides 表、要认得 @引用与
// 档位名），而那套判据在这个模块里只有一份（omoUse）。给界面开一个「随手改」的
// 口子等于再造一份写语义——两份迟早对同一份 omo-slots.json 给出不同答案。
// 卡片上写清楚去哪儿改就够了（见 Broken 那条同款理由）。

import (
	i18n "github.com/rzbdz/newgate/lib/i18n"
	"github.com/rzbdz/newgate/lib/view"
)

// slotsConceptID 是这张卡片的稳定身份。
const slotsConceptID = "opencode-omo.slots"

func omoConcepts() ([]view.Concept, error) {
	reg := ReadOmoSlots()
	if reg == nil {
		// 没有注册表 = 还没接管过 omo。**照常报一张卡片**，写上原因与怎么生成
		// （与 CLI 的 omoRegistry 同一句话）：让它从列表里消失的话，用户会以为
		// 这个模块不存在，而不是「还没接管过」。
		return []view.Concept{{
			ID:    slotsConceptID,
			Kind:  view.KindTable,
			Title: i18n.T("omo slot bindings", nil),
			Broken: i18n.T("no slot registry at {file} — generated by one takeover: newgate on opencode",
				i18n.A{"file": SlotsFile()}),
		}}, nil
	}

	table := view.Table{
		Columns: []view.Column{
			// 槽位键（omo-sisyphus / cat-deep）是**机器标记**：它是 profile 里
			// 直接可写的引用名，也是 `newgate omo` 认的身份，翻它等于让两个界面
			// 用两个名字说同一个槽位。
			{ID: "key", Label: i18n.T("slot key", nil)},
			{ID: "slot", Label: i18n.T("slot", nil)},
			{ID: "now", Label: i18n.T("now", nil)},
			{ID: "effective", Label: i18n.T("effective", nil)},
			{ID: "suggested", Label: i18n.T("suggested", nil)},
		},
		Rows: []map[string]view.Cell{},
	}
	for _, s := range reg.Slots {
		// OmoSlot.Key 是**存下来的**键（登记时算好的），不是 Slot.Key() 那个
		// 由 kind+name 现算的方法——两个类型，两个来源，别混。
		key := s.Key
		table.Rows = append(table.Rows, map[string]view.Cell{
			"key":  {Text: key},
			"slot": {Text: s.Kind + "/" + s.Name},
			"now":  dashIfEmpty(s.Current),
			// 「这个值来自 override」写进格子里，而不是像 CLI 那样打一个 `*`
			// 再在页脚解释：表没有页脚，一个没有解释的星号只会让人猜。
			"effective": effectiveCell(reg, key),
			"suggested": suggestedCell(s),
		})
	}
	return []view.Concept{{
		ID:    slotsConceptID,
		Kind:  view.KindTable,
		Title: i18n.T("omo slot bindings", nil),
		Data:  table,
	}}, nil
}

// effectiveCell 是**实际生效**的那个绑定：overrides 最优先，其次看 mode。
func effectiveCell(reg *OmoSlots, key string) view.Cell {
	binding := reg.SlotBinding(key)
	if binding == "" {
		return view.Cell{Text: "-"}
	}
	if v, ok := reg.Overrides[key]; ok && v != "" {
		return view.Cell{Text: i18n.T("{binding} (override)", i18n.A{"binding": binding})}
	}
	return view.Cell{Text: binding}
}

// suggestedCell 是建议的体格，**与现状不一致时标黄**。
//
// 判据与 CLI 一字不差（`s.Suggested != "" && s.Suggested != s.Current`）：两个
// 界面对「哪些槽位与建议不符」必须给出同一个答案，否则用户会在终端里看到三条、
// 在网页上看到两条，然后开始怀疑数据本身。
func suggestedCell(s OmoSlot) view.Cell {
	if s.Suggested == "" {
		return view.Cell{Text: "-"}
	}
	if s.Suggested != s.Current {
		return view.Cell{Text: s.Suggested, Tone: view.ToneWarn}
	}
	return view.Cell{Text: s.Suggested}
}

// dashIfEmpty 给空值一个显式的占位符：空格子读起来像「这里出了问题」，
// 而它其实只是在说「没有」。
func dashIfEmpty(s string) view.Cell {
	if s == "" {
		return view.Cell{Text: "-"}
	}
	return view.Cell{Text: s}
}
