// Code generated by tools/distgen. DO NOT EDIT.
//
// 由仓库根的规格书（dist*.json）编译而来：每条 app.Selection 就是一份规格书
// 要装的东西——自己的模块 + 要关掉的内核模块。构建时用
// -ldflags -X main.spec=<文件名> 选一份，DefaultSpec 是没注入时的兜底。
//
// 规格书里的 `"disable": ["*"]` 编成 app.Selection.AllCore：内核自带的全都不要，
// 只留关不掉的那些（组合根自己要用的端口）。

package manifest

import (
	"fmt"
	"strings"

	ext_claudecode "github.com/rzbdz/newgate-ext/modules/claudecode"
	ext_claudecode_deepseek "github.com/rzbdz/newgate-ext/modules/claudecode_deepseek"
	ext_claudecode_glm "github.com/rzbdz/newgate-ext/modules/claudecode_glm"
	ext_deepseek "github.com/rzbdz/newgate-ext/modules/deepseek"
	ext_glm "github.com/rzbdz/newgate-ext/modules/glm"
	ext_hello "github.com/rzbdz/newgate-ext/modules/hello"
	ext_opencode "github.com/rzbdz/newgate-ext/modules/opencode"
	ext_opencodeomo "github.com/rzbdz/newgate-ext/modules/opencodeomo"
	ext_simple_cli "github.com/rzbdz/newgate-ext/modules/simple-cli"
	ext_tui "github.com/rzbdz/newgate-ext/modules/tui"
	app "github.com/rzbdz/newgate/app"
	modules "github.com/rzbdz/newgate/component"
)

// DefaultSpec 是没注入 -X main.spec 时用的规格书。
//
// 它让 `go run ./cmd/newgate` 与 `go test ./...` 不用先编一遍就能跑——
// 默认那份就是仓库根的主规格书，与正式产物一致。
const DefaultSpec = "dist.json"

// Specs 是仓库根每份规格书各自的装配选择。
func Specs() map[string]app.Selection {
	return map[string]app.Selection{
		"dist-hello.json": {
			AllCore: true,
			Extra: []app.Entry{
				{Dir: "hello", Component: ext_hello.New()},
			},
		},
		"dist-simple-cli.json": {
			Disable: []string{"cli"},
			Extra: []app.Entry{
				{Dir: "simple-cli", Component: ext_simple_cli.New()},
				{Dir: "deepseek", Component: ext_deepseek.New()},
				{Dir: "glm", Component: ext_glm.New()},
				{Dir: "claudecode_deepseek", Component: ext_claudecode_deepseek.New()},
				{Dir: "claudecode_glm", Component: ext_claudecode_glm.New()},
				{Dir: "claudecode", Component: ext_claudecode.New()},
				{Dir: "opencode", Component: ext_opencode.New()},
				{Dir: "opencodeomo", Component: ext_opencodeomo.New()},
			},
		},
		"dist.json": {
			Extra: []app.Entry{
				{Dir: "tui", Component: ext_tui.New()},
				{Dir: "deepseek", Component: ext_deepseek.New()},
				{Dir: "glm", Component: ext_glm.New()},
				{Dir: "claudecode_deepseek", Component: ext_claudecode_deepseek.New()},
				{Dir: "claudecode_glm", Component: ext_claudecode_glm.New()},
				{Dir: "claudecode", Component: ext_claudecode.New()},
				{Dir: "opencode", Component: ext_opencode.New()},
				{Dir: "opencodeomo", Component: ext_opencodeomo.New()},
			},
		},
	}
}

// SpecNames 列出全部规格书名，按文件名排序。
func SpecNames() []string { return []string{"dist-hello.json", "dist-simple-cli.json", "dist.json"} }

// Loader 按规格书名装图。名字认不出来就**报错**，不退回默认那份：
// 「我明明编的是简单版，怎么界面上有两个 ui」这种问题，值得在启动的第一秒
// 就说清楚，而不是让用户自己去比对二进制。
type Loader struct{ Spec string }

func (l Loader) Load() ([]modules.Component, error) {
	name := l.Spec
	if name == "" {
		name = DefaultSpec
	}
	sel, ok := Specs()[name]
	if !ok {
		return nil, fmt.Errorf("没有叫 %q 的规格书（可用：%s）", name, strings.Join(SpecNames(), ", "))
	}
	return sel.Load()
}
